env:
  es2021: true
  node: true
  screeps/screeps: true
extends: "google"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  require-jsdoc: 0
  max-len:
    - error
    - code: 120
plugins:
 - screeps
