{
 "title": "Shard3",
 "tags": [ "screeps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Colony", "query": "stats.gauges.colonies.*" }
  ]
 },
 "panels": [
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "Usage" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cpu.used, 'Used')"
    },
    {
     "target": "alias(stats.gauges.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(stats.gauges.cpu.limit, 'Limit')"
    },
    {
     "target": "alias(movingAverage(stats.gauges.cpu.used, '1hour'), 'Used 1h avg')"
    }
   ]
  },
  {
   "title": "Current Bucket",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.cpu.bucket" }
   ]
  },
  {
   "title": "Ticks Per Stats Update",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(stats.gauges.time), 'Ticks Per Update')"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.gcl.level" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(stats.gauges.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(stats.gauges.gcl.progressTotal, #B), #C)"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(stats.gauges.gcl.progress), #B), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Creeps by Role",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.creeps.*, 3)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.resources.*, 3)"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.topics.*, 3)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "Colony" },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 33 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 66 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 99 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 99 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 132 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 132 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 165 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 165 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  },
  { "title": "$Colony", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "RCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 198 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.colonies.$Colony.rooms.*.controllerLevel)"
    }
   ]
  },
  {
   "title": "Time to Next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 198 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), #B), #C)",
     "targetFull": "divideSeries(diffSeries(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgressTotal), sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), scaleToSeconds(movingAverage(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), '1hour'), 1))"
    }
   ]
  },
  {
   "title": "GCL Upgrade",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), 'GCL per tick')",
     "targetFull": "alias(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), 'GCL per tick')"
    },
    {
     "target": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), #B), '1hour'), '1hr Moving Average')",
     "targetFull": "alias(movingAverage(divideSeries(nonNegativeDerivative(sumSeries(stats.gauges.colonies.$Colony.rooms.*.controllerProgress)), derivative(stats.gauges.time)), '1hour'), '1hr Moving Average')"
    }
   ]
  },
  {
   "title": "Stored Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage')"
    },
    {
     "refCount": -1,
     "target": "alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')"
    },
    {
     "target": "alias(sumSeries(#A, #B, #C), \"Total\")",
     "targetFull": "alias(sumSeries(alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.storageEnergy), 'Storage'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.energyAvailable), 'Spawns and Extensions'), alias(sumSeries(stats.gauges.colonies.$Colony.rooms.*.terminalEnergy), 'Terminals')), \"Total\")"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.*, 5)"
    }
   ]
  },
  {
   "title": "Energy left in source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.energy, 5, 7)"
    }
   ]
  },
  {
   "title": "Logistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.desiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.pidDesiredHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.topics.task_haul, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.numHaulers, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.haulerSetpoint, 4)"
    }
   ]
  },
  {
   "title": "Source Container Free Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.rooms.*.sources.*.containerFree, 5, 7)"
    }
   ]
  },
  {
   "title": "Spawning & Boost Prep",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.booster.*, 5)"
    },
    {
     "target": "aliasByNode(stats.gauges.colonies.$Colony.spawner.*.isSpawning, 5)"
    }
   ]
  }
 ]
}