FROM docker.pedanticorderliness.com/screeps-private-server:main

# hacky, should look at other ways to get the branch's bot into the image
# complicated by the fact that the dist dir isn't checked in
COPY dist /pserver/node_modules/screeps-bot-choreographer/dist
