# name: open pr
# on:
#   pull_request:
#     types: [opened, reopened]
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
#     - name: Check out code
#       uses: actions/checkout@v3
#     - name: Install Grunt
#       run: npm install -g grunt-cli
#     - name: Get .screeps.json file from secret
#       env:
#         DOT_SCREEPS_JSON: ${{ secrets.DOT_SCREEPS_JSON }}
#       run: echo $DOT_SCREEPS_JSON > .screeps.json
#     - name: Install dependencies
#       run: npm install
#     - name: Test
#       run: grunt test
#     - name: Build
#       run: grunt build
#     - name: Login to Docker repo
#       uses: docker/login-action@v2
#       with:
#         registry: docker.pedanticorderliness.com
#         username: ${{ secrets.DOCKER_REG_USER }}
#         password: ${{ secrets.DOCKER_REG_PASS }}
#     - name: Build and push Docker images
#       uses: docker/build-push-action@v3
#       with:
#         file: ./k8s/Dockerfile
#         context: .
#         push: true
#         tags: |
#           docker.pedanticorderliness.com/screeps-private-server:${{ github.sha }}
#           docker.pedanticorderliness.com/screeps-private-server:${{ github.head_ref }}
#     - name: Create Screeps Server Resource
#       run: |
#         curl --fail -X POST -H "X-Access-Token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}" "https://actions.pedanticorderliness.com/resource/screeps/server?branch=${{ github.head_ref }}&tag=${{ github.sha }}"
